# services
services:
  # redis-cache:
  #   image: redis-cache:inception
  #   build: ./requirements/bonus/redis-cache/
  #   container_name: redis-cache
  #   healthcheck:
  #     test: redis-cli -h redis-cache ping
  #     interval: 3s
  #     timeout: 2s
  #     retries: 20
  #   networks:
  #     - our_net
  #   restart: on-failure
  #   env_file:
  #     - .env

  mariadb:
    image: mariadb:inception
    build: ./requirements/mariadb/
    container_name: mariadb
    healthcheck:
      test: cat $MARIADB_HEALTHY_FILE
      interval: 2s
      timeout: 1s
      retries: 20
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - our_net
    restart: on-failure
    env_file:
      - .env

  wordpress:
    image: wordpress:inception
    build: ./requirements/wordpress/
    container_name: wordpress
    healthcheck:
      test: cat $WP_HEALTHY_FILE
      interval: 3s
      timeout: 1s
      retries: 20
    depends_on:
      mariadb:
        condition: service_healthy
      # redis-cache:
      #   condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - our_net
    restart: on-failure
    env_file:
      - .env

  adminer:
    image: adminer:inception
    build: ./requirements/bonus/adminer/
    container_name: adminer
    healthcheck:
      test: cat $ADMINER_HEALTHY_FILE
      interval: 2s
      timeout: 1s
      retries: 20
    volumes:
      - adminer_data:/var/www/html
    networks:
      - our_net
    restart: on-failure
    env_file:
      - .env

  nginx:
    image: nginx:inception
    build: ./requirements/nginx/
    container_name: nginx
    depends_on:
      adminer:
        condition: service_healthy
      wordpress:
        condition: service_healthy
    networks:
      - our_net
    ports:
      # - $NGINX_PORT:$NGINX_PORT
      - 80:80
    restart: on-failure

  # filebrowser:
  #   image: filebrowser:inception
  #   build: ./requirements/bonus/filebrowser/
  #   container_name: filebrowser
  #   volumes:
  #     - filebrowser_data:$FILEBROWSER_DIR
  #   networks:
  #     - our_net
  #   restart: on-failure
  #   env_file:
  #     - .env

  # vsftpd:
  #   image: vsftpd:inception
  #   build: ./requirements/bonus/vsftpd/
  #   container_name: vsftpd
  #   volumes:
  #     - wordpress_data:/home/$FTP_USER
  #   ports:
  #     - $FTP_PORT:$FTP_PORT
  #   networks:
  #     - our_net
  #   restart: on-failure
  #   env_file:
  #     - .env

# volumes
volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /workspaces/Inception/data/wordpress
      o: bind

  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /workspaces/Inception/data/mariadb
      o: bind

  adminer_data:
    name: adminer_data
    driver: local
    driver_opts:
      type: none
      device: /workspaces/Inception/data/adminer
      o: bind

  filebrowser_data:
    name: filebrowser_data
    driver: local
    driver_opts:
      type: none
      device: /workspaces/Inception/data/filebrowser
      o: bind

# networks
networks:
  our_net:
    name: inception_network
    driver: bridge