# services
services:
  redis-cache:
    image: redis-cache:inception
    build: ./requirements/bonus/redis-cache/
    container_name: redis-cache
    networks:
      - our_net
    restart: on-failure
    env_file:
      - .env

  mariadb:
    image: mariadb:inception
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - our_net
    restart: on-failure
    env_file:
      - .env

  wordpress:
    image: wordpress:inception
    build: ./requirements/wordpress/
    container_name: wordpress
    depends_on:
      - mariadb
      - redis-cache
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - our_net
    restart: on-failure
    env_file:
      - .env

  adminer:
    image: adminer:inception
    build: ./requirements/bonus/adminer/
    container_name: adminer
    volumes:
      - adminer_data:/var/www/html
    networks:
      - our_net
    restart: on-failure
    env_file:
      - .env

  nginx:
    image: nginx:inception
    build: ./requirements/nginx/
    container_name: nginx
    depends_on:
      - adminer
      - wordpress
    networks:
      - our_net
    ports:
      - "443:443"
    restart: on-failure
  
  filebrowser:
    image: filebrowser:inception
    build: ./requirements/bonus/filebrowser/
    container_name: filebrowser
    networks:
      - our_net
    ports:
      - $FILEBROWSER_PORT:$FILEBROWSER_PORT
    restart: on-failure
    env_file:
      - .env

  vsftpd:
    image: vsftpd:inception
    build: ./requirements/bonus/vsftpd/
    container_name: vsftpd
    volumes:
      - wordpress_data:/home/$FTP_USER
    ports:
      - "21:21"
    networks:
      - our_net
    restart: on-failure
    env_file:
      - .env

# volumes
volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/taeypark/data/wordpress
      o: bind

  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/taeypark/data/mariadb
      o: bind

  adminer_data:
    name: adminer_data
    driver: local
    driver_opts:
      type: none
      device: /home/taeypark/data/adminer
      o: bind

# networks
networks:
  our_net:
    name: inception_network