services:
  nginx:
    image: nginx:inception
    build: ./requirements/nginx/
    depends_on:
      - mariadb
      - wordpress
    container_name: nginx
    networks:
      - our_net
    ports:
      - "443:443"
    restart: on-failure

  mariadb:
    image: mariadb:inception
    build: ./requirements/mariadb/
    container_name: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - our_net
    restart: on-failure
    env_file:
      - .env

  wordpress:
    image: wordpress:inception
    build: ./requirements/wordpress/
    depends_on:
      - mariadb
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - our_net
    restart: on-failure
    env_file:
      - .env

  vsftpd:
    image: vsftpd:inception
    build: ./requirements/bonus/vsftpd/
    container_name: vsftpd
    volumes:
      - wordpress_data:/home/$FTP_USER
    ports:
      - "21:21"
    networks:
      - our_net
    restart: on-failure
    env_file:
      - .env

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: none
      device: /home/taeypark/data/wordpress
      o: bind

  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: none
      device: /home/taeypark/data/mariadb
      o: bind

networks:
  our_net:
    name: inception_network